# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GH Pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build output
      run: |
        mkdir www
        cp ./CNAME ./www/CNAME
        make docs
        cp output/* ./www/*
        cp ./www/developer-experience-spec.html ./www/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GHP_TOKEN }}
        publish_dir: ./www
